name: deploy

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Deploy to SSH
        uses: appleboy/ssh-action@master
        with:
          host: 103.67.186.27
          username: ayat
          password: Brexdmcs991!
          sync: true
          script: |
            DIR="/home/ayat/binar-api" \
            && cd $DIR \
            && git pull origin main \
            && npm install \
            && pm2 restart app