name: deploy

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Deploy to SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 103.67.186.27
          port: 22
          username: ayat
          password: Brexdcms991!
          sync: true
          script: |
            DIR="/home/ayat/binar-api" \
            BINPATH="/home/ayat/.local/share/fnm/node-versions/v18.17.1/installation/bin" \
            && cd $DIR \
            && git pull origin main \
            && source ~/.bashrc \
            && $BINPATH/npm ci \
            && $BINPATH/pm2 restart app